# Generated by Django 3.1 on 2020-10-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('hospital_name', models.CharField(max_length=500)),
                ('hospital_type', models.CharField(max_length=500)),
                ('streetNum', models.IntegerField()),
                ('roadName', models.CharField(max_length=500)),
                ('roadType', models.CharField(max_length=500)),
                ('area', models.CharField(max_length=500)),
                ('postcode', models.IntegerField()),
                ('state', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('choiceA', models.CharField(max_length=500)),
                ('choiceB', models.CharField(max_length=500)),
                ('choiceC', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=32)),
                ('feedbackA', models.CharField(max_length=500)),
                ('feedbackB', models.CharField(max_length=500)),
                ('feedbackC', models.CharField(max_length=500)),
                ('questionId', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('keyword', models.CharField(max_length=100)),
                ('imageurl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=1000)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctOrNot', models.BooleanField()),
                ('userChoice', models.CharField(max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
    ]
