# Generated by Django 3.1 on 2020-10-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital1',
        ),
    ]
