# Generated by Django 3.1 on 2020-10-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_delete_hospital1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_Question',
        ),
    ]
