# Generated by Django 3.1 on 2020-10-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine_recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=1000)),
                ('prevenar_13_total_dose', models.CharField(max_length=100)),
                ('prevenar_13_detail_plan', models.CharField(max_length=1000)),
                ('Pneumovax_23_total_dose', models.CharField(max_length=100)),
                ('Pneumovax_23_detail_plan', models.CharField(max_length=1000)),
                ('special_conditon', models.CharField(max_length=1000)),
            ],
        ),
    ]
