# Generated by Django 3.1 on 2020-10-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vaccine', '0002_vaccine_recommend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccine_recommend',
        ),
    ]
