# Generated by Django 3.1 on 2020-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('clinic_type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('suburb', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.CharField(max_length=500)),
            ],
        ),
    ]
